### ISSUE TITLE
Discord loading screen creates issue in log file

### ISSUE THREAD

**Issue by omthakare16** [Waishnav/Watcher#10]
The loading window name of discord is consist \n Characters , due to that the format of log file is getting unorganized .

**Comment by Waishnav** [comment]
Can you provide screenshot so that I can understand the issue

**Comment by omthakare16** [comment]
![image](https://user-images.githubusercontent.com/83799380/175802851-7274ae31-2715-49fc-bbb7-f64b18f2f921.png)

**Comment by Waishnav** [comment]
For some reason, xdotool is returning string containing "\n" character for Discord Splash screen which is making raw-data file messy...
Will solve this edge case in next commit
