### ISSUE TITLE
make CONTRIBUTING.md 

### ISSUE THREAD

**Issue by Waishnav** [Waishnav/Watcher#16]
As Hactoberfest is about to start, to make this project open for contribution write CONTRIBUTING.md so that other fellow devs can understand the project structure and v1.0 branch and v2.0 branch, and the main branch and the workflow of making PR and merging PR into respective branches.

**Comment by Rituraj-13** [comment]
Hey, I want to contribute on this. So can you please assign this to me?

**Comment by Sarabjeet108** [comment]
I would like to work on this issue. Can you please assign it to me?

**Comment by Waishnav** [comment]
@omthakare16 are you working on this issue or not??

**Comment by omthakare16** [comment]
Yes , full power

**Comment by omthakare16** [comment]
Issue Resolved in PR #23 .

**Comment by Subhojit666** [comment]
I would like to work on this issue. Can you please assign it to me?
