### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by Waishnav** [Waishnav/Watcher#19]
Implement watcher for macOS.

**Things to consider before implementation**
-- You need to make the module for accessing Active app-name or you can use dependency.
-- So you'll have to make changes in src/Watcher/get_Windows.py

**Comment by mmdbalkhi** [comment]
Hey, I wanna work on it! can I?

**Comment by Waishnav** [comment]
Yes, you can start working from now.
Hit me up if there is any problem
