### ISSUE TITLE
switch to python3 in shebang 

### ISSUE THREAD

**Issue by Waishnav** [Waishnav/Watcher#20]
Make changes in the `src/bin/watcher` file so that watcher will implicitly use python3 as an interpreter.
Also, add python3 as a dependency in README.md

**Comment by VarenyaJ** [comment]
Is changing the shebang from <#!/usr/bin/python> to <#!/usr/bin/python3> what you mean?

**Comment by Waishnav** [comment]
Yes

**Comment by ujjwall-R** [comment]
I have created a PR, please look into it
