### ISSUE TITLE
Fix: shorten the app-name in "watcher -ds" result

### ISSUE THREAD

**Issue by Waishnav** [Waishnav/Watcher#24]
Make the below string shorter like this `Polkit-kde-authentication...` and eventually fix the layout issue.

<img src="https://user-images.githubusercontent.com/86405648/194922265-f9ad89a1-fd1f-4feb-8338-82b82bd430c4.png" height=auto width=600px >

**Comment by ujjwall-R** [comment]
I created a pull request. Please look into it.
I created a function to truncate the long strings and used it to set the width 22.

**Comment by ujjwall-R** [comment]
If required we can edit the width to 22-8=14. But I think that is not required. Is it?

**Comment by Waishnav** [comment]
> If required we can edit the width to 22-8=14. But I think that is not required. Is it?

I don't think it is necessary as sometime the appname return with the help of xdotool comes out length more than 20 and I've observed that middle part of that string is imp.

**Comment by Waishnav** [comment]
@ujjwall-R Thanks for contributing and have a good day ahead.
