### ISSUE TITLE
v2.0 issue as the day changed 

### ISSUE THREAD

**Issue by Waishnav** [Waishnav/Watcher#26]
First, read COTRIBUTING.md to get an overall idea of v1.0 and v2.0 and their differences.

**Issue Explained**
At midnight of the next day (after 24:00), the previous day's Data (which is a dictionary containing the app name and its usage) get copied to the next day so we get the previous day's usage in the next day as well.

**Where to work**
You need to first clone the v2.0 branch after forking the repo.
And then make changes in `src/Watcher/watch_log.py` according to issue.

**Comment by PawanPatil19** [comment]
I would like to work on this issue

**Comment by Waishnav** [comment]
@PawanPatil19  Hey are you working on this issue or not ??
If you need any help then do ask it

**Comment by PawanPatil19** [comment]
Sorry for the delay... made a pull request for the above issue
