### ISSUE TITLE
False usage is showing on week -summary command in v1.0

### ISSUE THREAD

**Issue by Waishnav** [Waishnav/Watcher#27]
|                                          watcher -ws result                                        |                                        watcher -ds result                                         |
| :-------------------------------------------------------------------------------------------: | :-------------------------------------------------------------------------------------------: |
| ![](https://user-images.githubusercontent.com/86405648/195031383-e712fccc-23f0-40b8-859f-4e7d63c01b67.png) |  ![](https://user-images.githubusercontent.com/86405648/195032139-e4979ef7-d3f1-41fa-afee-e1b771268fa3.png) |

As a result, we are getting twice the value of actual time spent. The image on the right side is showing the correct result of daily usage.

Before going to start working on issue clone v1.0 branch instead of main branch. and do changes according to an issue.

**Comment by ujjwall-R** [comment]
I will like to work on this issue.
I just have to reduce the time shown by "watcher -ws" comand by 2, right?

**Comment by ujjwall-R** [comment]
I created a pull request in the v1.0 branch. Please look into it.
