### ISSUE TITLE
Updating your README.md file and adding CODE_OF_CONDUCT.md 

### ISSUE THREAD

**Issue by Sowham-3098** [Waishnav/Watcher#29]
I want to add How to Contribute ,as it will be helpful for beginners and also adding contributers profiles into it and also want to add CODE_OF_CONDUCT.md

**Comment by Sowham-3098** [comment]
@Waishnav please assign me this task

**Comment by Waishnav** [comment]
At this point, it's not necessary IMO.
If you still want to work then convince me to change my decision.
What things are you gonna put in the doc??

**Comment by Waishnav** [comment]
hey @Sowham-3098 you can start working on this issue. Before that you make sure not to use any template do give personalize touch.
