### ISSUE TITLE
Segmentation fault after some usage

### ISSUE THREAD

**Issue by siduck** [Waishnav/Watcher#3]
![image](https://user-images.githubusercontent.com/59060246/159145313-f28e2890-09d5-4754-bffc-44ef0e3865ba.png)

**Comment by Waishnav** [comment]
Even though segmentation fault is occurring, I think, log creation is still working, you can check it by ```cat ~/.cache/Watcher/raw_data/[date].csv```

**Comment by siduck** [comment]
yes it works but the segmentation fault scared me for a moment
