### ISSUE TITLE
Watcher-Website is in developement

### ISSUE THREAD

**Issue by omthakare16** [Waishnav/Watcher#32]
Watcher-web is a  project that serves as the watcher's landing page.
The goal of this landing page is to make people aware of their screen time and thus the watcher.
You might also find some hacktoberfest issues to contribute to there.
Wacther-web should be checked out.
Do check it out : [Wacther-website](https://github.com/Waishnav/Watcher-website).

**Comment by Waishnav** [comment]
If you want like to contribute then react to this message with wave-hand emoji.

**Comment by Khushi-design-20** [comment]
Hey, I would like to contribute some design changes.

**Comment by omthakare16** [comment]
Feel free to provide the design we will look out, and will let you know what we think about it, if you use figma [here](https://github.com/Waishnav/Watcher-website/issues/1#issuecomment-1277940987) is the reference of current design.
