### ISSUE TITLE
Usage Feature Request

### ISSUE THREAD

**Issue by kherwata** [Waishnav/Watcher#8]
hello my friend and thanks for the great app 
i am requesting to update README file and add more information about usage ... because i got confused at first .. should i run `watcher --start` always when i start my pc or how does it work ? and thanks again

**Comment by Waishnav** [comment]
You don't need to manually run watcher --start command at each startup, if get run automatically through .xprofile file

**Comment by Waishnav** [comment]
Also thanks for appreciating my work.
Nowadays I'm not getting any time to develop some feature like AFK n all that stuff,
AFK feature half completed
